db_config: &db_config
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DB_HOST", 'db') %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  port: <%= ENV.fetch("DB_PORT", '5432') %>
  username: <%= ENV.fetch('DB_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('DB_PASSWORD', '') %>

development:
  default:
    db_config:
      <<: *db_config
      database: gorynich_default
  local:
    db_config:
      <<: *db_config
      database: gorynich_local
    secrets:
      uris:
        - http://localhost:3000
        - https://171f-80-68-11-146.eu.ngrok.io
  local1:
    db_config:
      <<: *db_config
      database: gorynich_local1
    secrets:
      uris:
        - http://test.local:3000
test:
  default:
    db_config:
      <<: *db_config
      database: gorynich_test_default
  local:
    db_config:
      <<: *db_config
      database: gorynich_test_local
    secrets:
      uris:
        - http://localhost:3000
        - https://171f-80-68-11-146.eu.ngrok.io
  local1:
    db_config:
      <<: *db_config
      database: gorynich_test_local1
    secrets:
      uris:
        - http://test.local
